# Generated by Django 4.2.3 on 2023-10-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to=organizator.models.organizator_directory_path)),
            ],
            options={
                'verbose_name': 'organizator',
                'verbose_name_plural': 'organizators',
            },
            bases=('user.user',),
        ),
    ]
