# Generated by Django 4.2.3 on 2023-10-13 11:55

from django.db import migrations, models
import django.db.models.deletion
import student.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('image', models.ImageField(blank=True, upload_to=student.models.student_directory_path)),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='club.club', verbose_name='club')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
