# Generated by Django 4.2.3 on 2023-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='coach.coach', verbose_name='coach'),
        ),
    ]
