# Generated by Django 4.2.3 on 2023-10-20 08:46

import coach.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to=coach.models.coach_directory_path)),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='club.club', verbose_name='club')),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coaches',
            },
            bases=('user.user',),
        ),
    ]
