# Generated by Django 4.2.3 on 2023-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='achievement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='achievement'),
        ),
    ]
