# Generated by Django 4.2.3 on 2023-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('coach', 'COACH'), ('organizator', 'ORGANIZATOR'), ('president', 'PRESIDENT')], max_length=20, null=True),
        ),
    ]
