# Generated by Django 4.2.3 on 2023-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('location', models.CharField(max_length=30, verbose_name='location')),
                ('competition_type', models.CharField(choices=[('republic', 'Republic'), ('regional', 'Regional')], max_length=20)),
                ('region', models.CharField(choices=[('abai_region', 'Abai region'), ('akmola_region', 'Akmola region'), ('aktobe_region', 'Aktobe Region'), ('almaty_city', 'Almaty city'), ('almaty_region', 'Almaty region'), ('astana_city', 'Astana city'), ('atyrau_region', 'Atyrau region'), ('baikonur_city', 'Baikonur city'), ('east_kazakhstan_region', 'East Kazakhstan region'), ('jambyl_region', 'Jambyl region'), ('jetisu_region', 'Jetisu region'), ('karaganda_region', 'Karaganda region'), ('kostanay_region', 'Kostanay region'), ('kyzylorda_region', 'Kyzylorda region'), ('mangystau_region', 'Mangystau region'), ('north_kazakhstan_region', 'North Kazakhstan region'), ('pavlodar_region', 'Pavlodar region'), ('shymkent_city', 'Shymkent city'), ('turkistan_region', 'Turkistan region'), ('ulytau_region', 'Ulytau region'), ('west_kazakhstan_region', 'West Kazakhstan region')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_category', models.CharField(choices=[('16-17', '16-17'), ('14-15', '14-15'), ('12-13', '12-13'), ('10-11', '10-11'), ('8-9', '8-9'), ('6-7', '6-7')], max_length=5)),
                ('weight_category', models.CharField(choices=[('44kg', '44kg'), ('48kg', '48kg'), ('52kg', '52kg'), ('56kg', '56kg'), ('60kg', '60kg'), ('64kg', '64kg'), ('68kg', '68kg'), ('72kg', '72kg'), ('76kg', '76kg')], max_length=5)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.competition')),
            ],
        ),
    ]
