# Generated by Django 4.2.3 on 2023-11-29 20:25

import competition.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('competition_type', models.CharField(choices=[('republic', 'Republic'), ('regional', 'Regional')], max_length=20)),
                ('location', models.CharField(max_length=30, verbose_name='location')),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=competition.models.image_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_category', models.CharField(choices=[('16-17', '16-17'), ('14-15', '14-15'), ('12-13', '12-13'), ('10-11', '10-11'), ('8-9', '8-9'), ('6-7', '6-7')], max_length=5)),
                ('weight_category', models.CharField(choices=[('44kg', '44kg'), ('48kg', '48kg'), ('52kg', '52kg'), ('56kg', '56kg'), ('60kg', '60kg'), ('64kg', '64kg'), ('68kg', '68kg'), ('72kg', '72kg'), ('76kg', '76kg')], max_length=5)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.competition')),
            ],
        ),
    ]
