# Generated by Django 4.2.3 on 2023-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='student.student'),
        ),
        migrations.AddField(
            model_name='competition',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.federation'),
        ),
    ]
