# Generated by Django 4.2.3 on 2023-10-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='student.student'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_blue', to='competition.participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='competition.competition'),
        ),
        migrations.AddField(
            model_name='game',
            name='fight1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_1', to='competition.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='fight2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_2', to='competition.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_fight', to='competition.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_red', to='competition.participant'),
        ),
        migrations.AddField(
            model_name='competition',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.federation'),
        ),
    ]
