# Generated by Django 4.2.3 on 2023-10-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizator', '0001_initial'),
        ('competition', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organizators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizator.organizator'),
        ),
    ]
