# Generated by Django 4.2.3 on 2023-10-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
