# Generated by Django 4.2.3 on 2023-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registration_finished',
            field=models.BooleanField(default=False),
        ),
    ]
