# Generated by Django 4.2.3 on 2023-11-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.region'),
        ),
    ]
