# Generated by Django 4.2.3 on 2023-10-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
        ('competition', '0004_game_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='blue_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_corner_fights', to='competition.participant'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_corner_fights', to='competition.participant'),
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('16-17', '16-17'), ('14-15', '14-15'), ('12-13', '12-13'), ('10-11', '10-11'), ('8-9', '8-9'), ('6-7', '6-7')], max_length=5)),
                ('weight_category', models.CharField(choices=[('44kg', '44kg'), ('48kg', '48kg'), ('52kg', '52kg'), ('56kg', '56kg'), ('60kg', '60kg'), ('64kg', '64kg'), ('68kg', '68kg'), ('72kg', '72kg'), ('76kg', '76kg')], max_length=5)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='competition.competition')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournaments', to='student.student')),
            ],
        ),
    ]
