# Generated by Django 4.2.3 on 2023-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Champion',
        ),
    ]
