# Generated by Django 4.2.3 on 2023-11-25 12:22

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_competition_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=competition.models.image_directory_path),
        ),
    ]
