# Generated by Django 4.2.3 on 2023-11-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_participant_place_delete_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant',
            new_name='student_info',
        ),
    ]
