# Generated by Django 4.2.3 on 2023-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_rename_participant_participant_student_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='organizators',
            new_name='organizator',
        ),
    ]
