# Generated by Django 4.2.3 on 2023-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('red_corner_winner', models.BooleanField(default=False)),
                ('blue_corner_winner', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('age_category', models.CharField(choices=[('16-17', '16-17'), ('14-15', '14-15'), ('12-13', '12-13'), ('10-11', '10-11'), ('8-9', '8-9'), ('6-7', '6-7')], max_length=5)),
                ('weight_category', models.CharField(choices=[('44kg', '44kg'), ('48kg', '48kg'), ('52kg', '52kg'), ('56kg', '56kg'), ('60kg', '60kg'), ('64kg', '64kg'), ('68kg', '68kg'), ('72kg', '72kg'), ('76kg', '76kg')], max_length=5)),
                ('blue_corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_corner_fights', to='competition.participant')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='competition.competition')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_fight', to='game.game')),
                ('red_corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_corner_fights', to='competition.participant')),
            ],
        ),
    ]
