# Generated by Django 4.2.3 on 2023-11-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_blue_corner_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
